Watching for file changes with StatReloader
Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Bad Request: /
[12/Aug/2024 22:57:49] "GET / HTTP/1.1" 400 66037
Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Bad Request: /
[12/Aug/2024 22:58:56] "GET / HTTP/1.1" 400 65382
Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Bad Request: /
[12/Aug/2024 22:58:59] "GET / HTTP/1.1" 400 66472
Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Bad Request: /
[12/Aug/2024 22:59:08] "GET / HTTP/1.1" 400 66334
Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Bad Request: /
[12/Aug/2024 22:59:20] "GET / HTTP/1.1" 400 66472
Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Bad Request: /
[12/Aug/2024 22:59:30] "GET / HTTP/1.1" 400 66334
Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Bad Request: /
[12/Aug/2024 22:59:35] "GET / HTTP/1.1" 400 65833
Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Bad Request: /
[12/Aug/2024 22:59:55] "GET / HTTP/1.1" 400 65800
Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Bad Request: /
[12/Aug/2024 23:00:00] "GET / HTTP/1.1" 400 67068
Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Bad Request: /
[12/Aug/2024 23:00:05] "GET / HTTP/1.1" 400 65833
Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Bad Request: /
[12/Aug/2024 23:00:28] "GET / HTTP/1.1" 400 66470
Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Bad Request: /
[12/Aug/2024 23:00:29] "GET / HTTP/1.1" 400 66688
Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Bad Request: /
[12/Aug/2024 23:00:35] "GET / HTTP/1.1" 400 66688
Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Bad Request: /
[12/Aug/2024 23:00:52] "GET / HTTP/1.1" 400 65386
Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Bad Request: /
[12/Aug/2024 23:29:24] "GET / HTTP/1.1" 400 65239
Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Bad Request: /
[12/Aug/2024 23:29:27] "GET / HTTP/1.1" 400 65243
Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Bad Request: /
[12/Aug/2024 23:29:28] "GET / HTTP/1.1" 400 65243
Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Bad Request: /
[12/Aug/2024 23:29:29] "GET / HTTP/1.1" 400 65239
Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.czebravisualdata.online'. You may need to add 'api.czebravisualdata.online' to ALLOWED_HOSTS.
Bad Request: /
[12/Aug/2024 23:43:13] "GET / HTTP/1.1" 400 65022
/home/czebravisualdata-api/htdocs/CzebraVisual/czebra/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 12, 2024 - 22:53:36
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 126, in inner_run
    autoreload.raise_last_exception()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'corsheaders'
/home/czebravisualdata-api/htdocs/CzebraVisual/czebra/settings.py changed, reloading.
Watching for file changes with StatReloader
Error: That port is already in use.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (staticfiles.W004) The directory '/home/czebravisualdata-api/htdocs/CzebraVisual/static' in the STATICFILES_DIRS setting does not exist.

System check identified 1 issue (0 silenced).
[12/Aug/2024 17:56:43] "GET /api/users/ HTTP/1.1" 200 5580
[12/Aug/2024 17:56:51] "GET /api/users/ HTTP/1.1" 200 5580
Not Found: /api/token
[12/Aug/2024 18:19:25] "GET /api/token HTTP/1.1" 404 2524
[12/Aug/2024 18:20:29] "GET /api/users/users/ HTTP/1.1" 200 6235
[12/Aug/2024 18:20:32] "GET /api/users/notifications/ HTTP/1.1" 200 5429
Not Found: /api/REQUESTS/
[12/Aug/2024 18:21:01] "GET /api/REQUESTS/ HTTP/1.1" 404 2536
Not Found: /api/REQUEST/
[12/Aug/2024 18:21:04] "GET /api/REQUEST/ HTTP/1.1" 404 2533
[12/Aug/2024 18:21:11] "GET /api/requests/ HTTP/1.1" 200 5607
/home/czebravisualdata-api/htdocs/CzebraVisual/czebra/urls.py changed, reloading.
Performing system checks...

August 12, 2024 - 17:56:40
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 531, in check
    for pattern in self.url_patterns:
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 718, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 711, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/czebra/urls.py", line 15, in <module>
    path('api/users/', include('users.urls')),
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users'
/home/czebravisualdata-api/htdocs/CzebraVisual/czebra/settings.py changed, reloading.
Performing system checks...

Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/manage.py", line 22, in <module>
    main()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 81, in __getattr__
    self._setup(name)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 68, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 166, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/czebra/settings.py", line 64, in <module>
    'SIGNING_KEY': settings.SECRET_KEY,
NameError: name 'settings' is not defined
Watching for file changes with StatReloader
Not Found: /
[12/Aug/2024 18:57:16] "GET / HTTP/1.1" 404 3162
Not Found: /
[12/Aug/2024 18:57:17] "GET / HTTP/1.1" 404 3162
Watching for file changes with StatReloader
Error: That port is already in use.
[12/Aug/2024 19:03:38] "GET /api/requests/companies/ HTTP/1.1" 200 13156
[12/Aug/2024 19:08:30] "OPTIONS /api/requests/companies/ HTTP/1.1" 200 0
[12/Aug/2024 19:08:30] "OPTIONS /api/requests/companies/ HTTP/1.1" 200 0
Forbidden: /api/requests/companies/
[12/Aug/2024 19:08:30] "GET /api/requests/companies/ HTTP/1.1" 403 183
Forbidden: /api/requests/companies/
[12/Aug/2024 19:08:30] "GET /api/requests/companies/ HTTP/1.1" 403 183
Forbidden: /api/requests/companies/
[12/Aug/2024 19:08:45] "POST /api/requests/companies/ HTTP/1.1" 403 183
Bad Request: /api/requests/companies/
[12/Aug/2024 19:10:02] "POST /api/requests/companies/ HTTP/1.1" 400 13433
[12/Aug/2024 19:10:33] "POST /api/requests/companies/ HTTP/1.1" 201 14090
Forbidden: /api/requests/companies/
[12/Aug/2024 19:10:36] "GET /api/requests/companies/ HTTP/1.1" 403 183
Forbidden: /api/requests/companies/
[12/Aug/2024 19:10:36] "GET /api/requests/companies/ HTTP/1.1" 403 183
Forbidden: /api/requests/companies/
[12/Aug/2024 19:10:37] "GET /api/requests/companies/ HTTP/1.1" 403 183
Forbidden: /api/requests/companies/
[12/Aug/2024 19:10:37] "GET /api/requests/companies/ HTTP/1.1" 403 183
Forbidden: /api/requests/companies/
[12/Aug/2024 19:10:38] "GET /api/requests/companies/ HTTP/1.1" 403 183
Forbidden: /api/requests/companies/
[12/Aug/2024 19:10:38] "GET /api/requests/companies/ HTTP/1.1" 403 183
Forbidden: /api/requests/companies/
[12/Aug/2024 19:13:54] "GET /api/requests/companies/ HTTP/1.1" 403 183
Forbidden: /api/requests/companies/
[12/Aug/2024 19:13:54] "GET /api/requests/companies/ HTTP/1.1" 403 183
Forbidden: /api/requests/companies/
[12/Aug/2024 19:14:02] "GET /api/requests/companies/ HTTP/1.1" 403 183
Forbidden: /api/requests/companies/
[12/Aug/2024 19:14:02] "GET /api/requests/companies/ HTTP/1.1" 403 183
[12/Aug/2024 19:20:28] "OPTIONS /api/requests/requests/ HTTP/1.1" 200 0
[12/Aug/2024 19:20:28] "OPTIONS /api/requests/requests/ HTTP/1.1" 200 0
Forbidden: /api/requests/requests/
[12/Aug/2024 19:20:28] "GET /api/requests/requests/ HTTP/1.1" 403 183
Forbidden: /api/requests/requests/
[12/Aug/2024 19:20:28] "GET /api/requests/requests/ HTTP/1.1" 403 183
Forbidden: /api/requests/companies/
[12/Aug/2024 19:20:34] "GET /api/requests/companies/ HTTP/1.1" 403 183
Forbidden: /api/requests/companies/
[12/Aug/2024 19:20:34] "GET /api/requests/companies/ HTTP/1.1" 403 183
[12/Aug/2024 19:20:40] "GET /api/requests/companies/ HTTP/1.1" 200 14040
Forbidden: /api/requests/companies/
[12/Aug/2024 19:22:39] "GET /api/requests/companies/ HTTP/1.1" 403 183
[12/Aug/2024 19:24:42] "POST /api-auth/logout/?next=/api/users/ HTTP/1.1" 302 0
[12/Aug/2024 19:24:42] "GET /api/users/ HTTP/1.1" 200 5643
[12/Aug/2024 19:24:42] "GET /api-auth/login/?next=/api/users/ HTTP/1.1" 200 2728
[12/Aug/2024 19:24:54] "POST /api-auth/login/ HTTP/1.1" 302 0
[12/Aug/2024 19:24:54] "GET /api/users/ HTTP/1.1" 200 6184
Forbidden: /api/requests/companies/
[12/Aug/2024 19:25:46] "GET /api/requests/companies/ HTTP/1.1" 403 183
Forbidden: /api/requests/requests/
[12/Aug/2024 19:25:46] "GET /api/requests/requests/ HTTP/1.1" 403 183
Forbidden: /api/requests/requests/
[12/Aug/2024 19:26:32] "GET /api/requests/requests/ HTTP/1.1" 403 183
Forbidden: /api/requests/companies/
[12/Aug/2024 19:26:32] "GET /api/requests/companies/ HTTP/1.1" 403 183
Forbidden: /api/requests/companies/
[12/Aug/2024 19:26:34] "GET /api/requests/companies/ HTTP/1.1" 403 183
Forbidden: /api/requests/companies/
[12/Aug/2024 19:26:34] "GET /api/requests/companies/ HTTP/1.1" 403 183
[12/Aug/2024 19:28:13] "GET /api/requests/ HTTP/1.1" 200 6214
Forbidden: /api/requests/requests/
[12/Aug/2024 19:28:38] "GET /api/requests/requests/ HTTP/1.1" 403 183
[12/Aug/2024 19:33:34] "GET /api/users/users/ HTTP/1.1" 200 22255
[12/Aug/2024 19:34:59] "OPTIONS /api/token/ HTTP/1.1" 200 0
Internal Server Error: /api/token/
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework_simplejwt/views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 445, in run_validation
    value = self.validate(value)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework_simplejwt/serializers.py", line 75, in validate
    refresh = self.get_token(self.user)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework_simplejwt/serializers.py", line 66, in get_token
    return cls.token_class.for_user(user)  # type: ignore
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework_simplejwt/tokens.py", line 283, in for_user
    token = super().for_user(user)  # type: ignore
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework_simplejwt/tokens.py", line 203, in for_user
    user_id = getattr(user, api_settings.USER_ID_FIELD)
AttributeError: 'User' object has no attribute 'id'
[12/Aug/2024 19:35:00] "POST /api/token/ HTTP/1.1" 500 118270
Method Not Allowed: /api/token/
[12/Aug/2024 19:35:56] "GET /api/token/ HTTP/1.1" 405 7718
Method Not Allowed: /api/token/
[12/Aug/2024 19:36:48] "GET /api/token/ HTTP/1.1" 405 7718
Internal Server Error: /api/token/
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework_simplejwt/views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 445, in run_validation
    value = self.validate(value)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework_simplejwt/serializers.py", line 75, in validate
    refresh = self.get_token(self.user)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework_simplejwt/serializers.py", line 66, in get_token
    return cls.token_class.for_user(user)  # type: ignore
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework_simplejwt/tokens.py", line 283, in for_user
    token = super().for_user(user)  # type: ignore
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework_simplejwt/tokens.py", line 203, in for_user
    user_id = getattr(user, api_settings.USER_ID_FIELD)
AttributeError: 'User' object has no attribute 'id'
[12/Aug/2024 19:36:51] "POST /api/token/ HTTP/1.1" 500 120961
/home/czebravisualdata-api/htdocs/CzebraVisual/czebra/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 12, 2024 - 18:51:37
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 12, 2024 - 19:38:22
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
[12/Aug/2024 19:38:58] "GET /api/requests/ HTTP/1.1" 200 6214
Method Not Allowed: /api/token/
[12/Aug/2024 19:39:09] "GET /api/token/ HTTP/1.1" 405 7718
[12/Aug/2024 19:39:13] "POST /api/token/ HTTP/1.1" 200 8162
[12/Aug/2024 19:39:19] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 19:39:19] "OPTIONS /api/users/users/ HTTP/1.1" 200 0
[12/Aug/2024 19:39:19] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 19:39:20] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 19:39:20] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 19:39:24] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 19:39:24] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 19:39:25] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 19:39:25] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 19:39:26] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 19:39:26] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 19:39:27] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 19:39:27] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 19:39:37] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 19:39:37] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 19:39:39] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 19:39:39] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 19:39:39] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 19:39:39] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 19:39:41] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 19:39:41] "GET /api/users/users/ HTTP/1.1" 200 1866
Unauthorized: /api/token/
[12/Aug/2024 19:39:44] "POST /api/token/ HTTP/1.1" 401 63
[12/Aug/2024 19:39:51] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 19:39:51] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 19:47:53] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 19:47:53] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 19:47:54] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 19:47:54] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 19:48:01] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 19:48:01] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 19:49:32] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 19:49:32] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 19:49:38] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 19:49:38] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 19:51:08] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 19:51:08] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 19:51:34] "GET /api/requests/requests/ HTTP/1.1" 200 2
[12/Aug/2024 19:51:34] "GET /api/requests/requests/ HTTP/1.1" 200 2
[12/Aug/2024 19:52:26] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 19:52:26] "GET /api/users/users/ HTTP/1.1" 200 1866
Not Found: /
[12/Aug/2024 20:15:16] "GET / HTTP/1.1" 404 3162
[12/Aug/2024 21:12:06] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 21:12:06] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 21:17:19] "OPTIONS /api/requests/companies/ HTTP/1.1" 200 0
[12/Aug/2024 21:17:19] "OPTIONS /api/requests/companies/ HTTP/1.1" 200 0
[12/Aug/2024 21:17:19] "GET /api/requests/companies/ HTTP/1.1" 200 352
[12/Aug/2024 21:17:19] "GET /api/requests/companies/ HTTP/1.1" 200 352
[12/Aug/2024 21:17:21] "GET /api/requests/requests/ HTTP/1.1" 200 2
[12/Aug/2024 21:17:21] "GET /api/requests/requests/ HTTP/1.1" 200 2
[12/Aug/2024 21:17:23] "GET /api/requests/companies/ HTTP/1.1" 200 352
[12/Aug/2024 21:17:23] "GET /api/requests/companies/ HTTP/1.1" 200 352
[12/Aug/2024 21:17:28] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 21:17:28] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 21:17:33] "GET /api/requests/companies/ HTTP/1.1" 200 352
[12/Aug/2024 21:17:33] "GET /api/requests/companies/ HTTP/1.1" 200 352
[12/Aug/2024 21:17:38] "OPTIONS /api/requests/companies/1/ HTTP/1.1" 200 0
[12/Aug/2024 21:17:38] "PUT /api/requests/companies/1/ HTTP/1.1" 200 350
[12/Aug/2024 21:17:38] "GET /api/requests/companies/ HTTP/1.1" 200 352
[12/Aug/2024 21:17:51] "GET /api/requests/companies/ HTTP/1.1" 200 352
[12/Aug/2024 21:17:51] "GET /api/requests/companies/ HTTP/1.1" 200 352
[12/Aug/2024 21:17:53] "GET /api/requests/companies/ HTTP/1.1" 200 352
[12/Aug/2024 21:17:53] "GET /api/requests/companies/ HTTP/1.1" 200 352
[12/Aug/2024 21:18:06] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 21:18:06] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 21:19:27] "GET /api/users/users/1 HTTP/1.1" 301 0
[12/Aug/2024 21:19:27] "GET /api/users/users/1/ HTTP/1.1" 200 21056
[12/Aug/2024 21:44:28] "OPTIONS /api/token/ HTTP/1.1" 200 0
[12/Aug/2024 21:44:28] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 21:44:28] "OPTIONS /api/users/users/ HTTP/1.1" 200 0
[12/Aug/2024 21:44:28] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 21:44:29] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 21:44:29] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 21:44:36] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 21:44:36] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 21:44:47] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 21:44:47] "GET /api/users/users/ HTTP/1.1" 200 1866
[12/Aug/2024 21:45:07] "GET /api/users/ HTTP/1.1" 200 6184
[12/Aug/2024 21:45:08] "GET /api/users/users/ HTTP/1.1" 200 22255
[12/Aug/2024 21:45:19] "PUT /api/users/users/1/ HTTP/1.1" 200 21103
[12/Aug/2024 21:45:27] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 21:45:27] "GET /api/users/users/ HTTP/1.1" 200 1867
[12/Aug/2024 21:45:33] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 21:45:33] "GET /api/users/users/ HTTP/1.1" 200 1867
[12/Aug/2024 21:46:52] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 21:46:52] "GET /api/users/users/ HTTP/1.1" 200 1867
[12/Aug/2024 21:47:04] "GET /api/users/users/ HTTP/1.1" 200 22276
[12/Aug/2024 21:47:38] "GET /api/users/users/4 HTTP/1.1" 301 0
[12/Aug/2024 21:47:38] "GET /api/users/users/4/ HTTP/1.1" 200 21196
[12/Aug/2024 21:47:40] "DELETE /api/users/users/4/ HTTP/1.1" 200 19805
[12/Aug/2024 21:47:41] "GET /api/users/users/ HTTP/1.1" 200 21318
Unauthorized: /api/token/
[12/Aug/2024 21:47:53] "POST /api/token/ HTTP/1.1" 401 63
Unauthorized: /api/token/
[12/Aug/2024 21:52:11] "POST /api/token/ HTTP/1.1" 401 63
/home/czebravisualdata-api/htdocs/CzebraVisual/czebra/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 12, 2024 - 19:38:30
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/home/czebravisualdata-api/htdocs/CzebraVisual/czebra/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 12, 2024 - 21:55:53
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Unauthorized: /api/token/
[12/Aug/2024 21:56:48] "POST /api/token/ HTTP/1.1" 401 63
[12/Aug/2024 21:56:53] "GET /api/users/users/ HTTP/1.1" 200 21318
Unauthorized: /api/token/
[12/Aug/2024 21:56:55] "POST /api/token/ HTTP/1.1" 401 63
Unauthorized: /api/token/
[12/Aug/2024 21:56:59] "POST /api/token/ HTTP/1.1" 401 63
Unauthorized: /api/token/
[12/Aug/2024 21:58:02] "POST /api/token/ HTTP/1.1" 401 63
/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 12, 2024 - 21:56:44
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
[12/Aug/2024 22:01:46] "GET /api/users/users/ HTTP/1.1" 200 22071
[12/Aug/2024 22:01:53] "GET /api/users/ HTTP/1.1" 200 6184
/home/czebravisualdata-api/htdocs/CzebraVisual/users/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 12, 2024 - 22:01:36
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/home/czebravisualdata-api/htdocs/CzebraVisual/users/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 12, 2024 - 22:03:44
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/home/czebravisualdata-api/htdocs/CzebraVisual/users/urls.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 12, 2024 - 22:03:55
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
[12/Aug/2024 22:04:00] "GET /api/users/ HTTP/1.1" 200 6561
[12/Aug/2024 22:04:01] "GET /api/users/divisions/ HTTP/1.1" 200 9229
[12/Aug/2024 22:04:12] "POST /api/users/divisions/ HTTP/1.1" 201 9353
[12/Aug/2024 22:04:18] "GET /api/users/division-users/ HTTP/1.1" 200 9343
[12/Aug/2024 22:05:51] "GET /api/users/division-users/ HTTP/1.1" 200 9343
[12/Aug/2024 22:06:18] "GET /api/users/division-users/ HTTP/1.1" 200 9343
/home/czebravisualdata-api/htdocs/CzebraVisual/users/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 12, 2024 - 22:03:59
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 531, in check
    for pattern in self.url_patterns:
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 718, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 711, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/czebra/urls.py", line 15, in <module>
    path('api/users/', include('users.urls')),
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/users/urls.py", line 3, in <module>
    from .views import UserViewSet, NotificationViewSet, DivisionViewSet, DivisionUserViewSet
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/users/views.py", line 3, in <module>
    from .serializers import UserSerializer, NotificationSerializer, DivisionSerializer, DivisionUserSerializer
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/users/serializers.py", line 20, in <module>
    class DivisionUserSerializer(serializers.ModelSerializer):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/users/serializers.py", line 21, in DivisionUserSerializer
    division = DivisionSerializer(read_only=True)
NameError: name 'DivisionSerializer' is not defined. Did you mean: 'DivisionUserSerializer'?
/home/czebravisualdata-api/htdocs/CzebraVisual/users/serializers.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
[12/Aug/2024 22:06:41] "GET /api/users/division-users/ HTTP/1.1" 200 10209
[12/Aug/2024 22:06:53] "GET /api/users/divisions/ HTTP/1.1" 200 9957
[12/Aug/2024 22:06:57] "GET /api/users/divisions/1 HTTP/1.1" 301 0
[12/Aug/2024 22:06:57] "GET /api/users/divisions/1/ HTTP/1.1" 200 11310
[12/Aug/2024 22:07:14] "PUT /api/users/divisions/1/ HTTP/1.1" 200 11316
[12/Aug/2024 22:07:18] "PUT /api/users/divisions/1/ HTTP/1.1" 200 11310
[12/Aug/2024 22:07:21] "GET /api/users/division-users/ HTTP/1.1" 200 10211
[12/Aug/2024 22:07:26] "POST /api/users/division-users/ HTTP/1.1" 201 10415
Forbidden: /api/users/users/
[12/Aug/2024 22:08:57] "GET /api/users/users/ HTTP/1.1" 403 183
Forbidden: /api/users/users/
[12/Aug/2024 22:12:47] "GET /api/users/users/ HTTP/1.1" 403 183
Unauthorized: /api/token/
[12/Aug/2024 22:15:30] "POST /api/token/ HTTP/1.1" 401 63
Not Found: /api
[12/Aug/2024 22:16:29] "GET /api HTTP/1.1" 404 3189
Method Not Allowed: /api/token/
[12/Aug/2024 22:16:35] "GET /api/token/ HTTP/1.1" 405 7718
Method Not Allowed: /api/token/refresh/
[12/Aug/2024 22:16:42] "GET /api/token/refresh/ HTTP/1.1" 405 7550
Unauthorized: /api/token/
[12/Aug/2024 22:17:13] "POST /api/token/ HTTP/1.1" 401 63
Unauthorized: /api/token/
[12/Aug/2024 22:19:06] "POST /api/token/ HTTP/1.1" 401 63
Unauthorized: /api/token/
[12/Aug/2024 22:19:19] "POST /api/token/ HTTP/1.1" 401 63
Unauthorized: /api/token/
[12/Aug/2024 22:19:32] "POST /api/token/ HTTP/1.1" 401 63
[12/Aug/2024 22:19:39] "GET /api/users/users/1/ HTTP/1.1" 200 21959
[12/Aug/2024 22:19:43] "PUT /api/users/users/1/ HTTP/1.1" 200 21963
Unauthorized: /api/token/
[12/Aug/2024 22:19:50] "POST /api/token/ HTTP/1.1" 401 63
[12/Aug/2024 22:19:55] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 22:20:00] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 22:20:00] "GET /api/users/users/ HTTP/1.1" 200 1343
[12/Aug/2024 22:20:00] "OPTIONS /api/users/division-users/ HTTP/1.1" 200 0
[12/Aug/2024 22:20:00] "GET /api/users/division-users/ HTTP/1.1" 200 95
[12/Aug/2024 22:22:34] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 22:22:34] "GET /api/users/users/ HTTP/1.1" 200 1343
[12/Aug/2024 22:22:34] "GET /api/users/division-users/ HTTP/1.1" 200 95
[12/Aug/2024 22:23:01] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 22:23:01] "GET /api/users/users/ HTTP/1.1" 200 1343
[12/Aug/2024 22:23:01] "GET /api/users/division-users/ HTTP/1.1" 200 95
[12/Aug/2024 22:23:21] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 22:23:21] "GET /api/users/users/ HTTP/1.1" 200 1343
[12/Aug/2024 22:23:21] "GET /api/users/division-users/ HTTP/1.1" 200 95
[12/Aug/2024 22:25:43] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 22:25:43] "GET /api/users/users/ HTTP/1.1" 200 1343
[12/Aug/2024 22:25:43] "GET /api/users/division-users/ HTTP/1.1" 200 95
[12/Aug/2024 22:26:28] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 22:26:28] "GET /api/users/users/ HTTP/1.1" 200 1343
[12/Aug/2024 22:26:28] "GET /api/users/division-users/ HTTP/1.1" 200 95
[12/Aug/2024 22:32:18] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 22:32:18] "GET /api/users/users/ HTTP/1.1" 200 1343
[12/Aug/2024 22:32:18] "GET /api/users/division-users/ HTTP/1.1" 200 95
[12/Aug/2024 22:32:24] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 22:32:24] "GET /api/users/users/ HTTP/1.1" 200 1343
[12/Aug/2024 22:32:24] "GET /api/users/division-users/ HTTP/1.1" 200 95
[12/Aug/2024 22:34:09] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 22:34:09] "GET /api/users/users/ HTTP/1.1" 200 1343
[12/Aug/2024 22:34:09] "GET /api/users/division-users/ HTTP/1.1" 200 95
[12/Aug/2024 22:34:40] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 22:34:40] "GET /api/users/users/ HTTP/1.1" 200 1343
[12/Aug/2024 22:34:40] "GET /api/users/division-users/ HTTP/1.1" 200 95
[12/Aug/2024 22:35:08] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 22:35:08] "GET /api/users/users/ HTTP/1.1" 200 1343
[12/Aug/2024 22:35:08] "GET /api/users/division-users/ HTTP/1.1" 200 95
[12/Aug/2024 22:35:13] "GET /api/requests/companies/ HTTP/1.1" 200 352
[12/Aug/2024 22:35:13] "GET /api/requests/companies/ HTTP/1.1" 200 352
[12/Aug/2024 22:35:16] "GET /api/requests/companies/ HTTP/1.1" 200 352
[12/Aug/2024 22:35:16] "GET /api/requests/companies/ HTTP/1.1" 200 352
[12/Aug/2024 22:44:52] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 22:44:52] "GET /api/users/users/ HTTP/1.1" 200 1343
[12/Aug/2024 22:44:52] "GET /api/users/division-users/ HTTP/1.1" 200 95
[12/Aug/2024 22:44:58] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 22:44:58] "GET /api/users/users/ HTTP/1.1" 200 1343
[12/Aug/2024 22:44:58] "GET /api/users/division-users/ HTTP/1.1" 200 95
[12/Aug/2024 22:46:23] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 22:46:23] "GET /api/users/users/ HTTP/1.1" 200 1343
[12/Aug/2024 22:46:24] "GET /api/users/division-users/ HTTP/1.1" 200 95
[12/Aug/2024 23:00:18] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 23:00:18] "GET /api/users/users/ HTTP/1.1" 200 1343
[12/Aug/2024 23:00:18] "GET /api/users/division-users/ HTTP/1.1" 200 95
[12/Aug/2024 23:01:40] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 23:01:40] "GET /api/users/users/ HTTP/1.1" 200 1343
[12/Aug/2024 23:01:41] "GET /api/users/division-users/ HTTP/1.1" 200 95
[12/Aug/2024 23:05:04] "OPTIONS /api/users/divisions/ HTTP/1.1" 200 0
[12/Aug/2024 23:05:04] "OPTIONS /api/users/division-users/?user=1 HTTP/1.1" 200 0
[12/Aug/2024 23:05:04] "OPTIONS /api/users/divisions/ HTTP/1.1" 200 0
[12/Aug/2024 23:05:04] "OPTIONS /api/users/division-users/?user=1 HTTP/1.1" 200 0
[12/Aug/2024 23:05:04] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:05:04] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:05:04] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:05:04] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:05:13] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:05:13] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:05:13] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:05:13] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:05:15] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:05:15] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:05:15] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:05:15] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:05:21] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 23:05:21] "GET /api/users/users/ HTTP/1.1" 200 1343
[12/Aug/2024 23:05:21] "GET /api/users/division-users/ HTTP/1.1" 200 95
[12/Aug/2024 23:05:37] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:05:37] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:05:38] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:05:38] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:05:42] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:05:42] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:05:42] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:05:42] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:05:43] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:05:43] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:05:43] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:05:43] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:05:57] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:05:57] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:05:57] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:05:57] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:06:06] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:06:06] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:06:06] "GET /api/requests/companies/ HTTP/1.1" 200 352
[12/Aug/2024 23:06:06] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:06:06] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:06:06] "GET /api/requests/companies/ HTTP/1.1" 200 352
[12/Aug/2024 23:06:10] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:06:10] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:06:10] "GET /api/requests/companies/ HTTP/1.1" 200 352
[12/Aug/2024 23:06:10] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:06:10] "GET /api/requests/companies/ HTTP/1.1" 200 352
[12/Aug/2024 23:06:10] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:06:36] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:06:36] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:06:55] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:06:55] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:07:09] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:07:09] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:07:33] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:07:33] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:07:40] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:07:40] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:07:40] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:07:40] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:07:45] "POST /api/token/ HTTP/1.1" 200 483
[12/Aug/2024 23:07:45] "GET /api/users/users/ HTTP/1.1" 200 1343
[12/Aug/2024 23:07:46] "GET /api/users/division-users/ HTTP/1.1" 200 95
[12/Aug/2024 23:07:46] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:07:46] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:07:46] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:07:46] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:58:38] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:58:38] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:58:43] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:58:43] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:58:47] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:58:47] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:58:47] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:58:47] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:58:54] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:58:54] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:59:11] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:59:11] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:59:14] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:59:14] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:59:14] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:59:14] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:59:15] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:59:15] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:59:15] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:59:15] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[12/Aug/2024 23:59:23] "GET /api/users/divisions/ HTTP/1.1" 200 55
[12/Aug/2024 23:59:23] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:01:11] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:01:11] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:01:11] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:01:11] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:01:31] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:01:31] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:01:31] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:01:31] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:01:48] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:01:48] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:01:48] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:01:48] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:01:57] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:01:57] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:01:57] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:01:57] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:03:37] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:03:37] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:03:37] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:03:37] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:03:47] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:03:47] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:03:47] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:03:47] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:03:49] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:03:49] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:03:49] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:03:49] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:03:52] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:03:52] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:03:52] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:03:52] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:03:53] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:03:53] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:03:53] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:03:53] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:04:02] "OPTIONS /api/token/ HTTP/1.1" 200 0
[13/Aug/2024 00:04:02] "POST /api/token/ HTTP/1.1" 200 483
[13/Aug/2024 00:04:02] "OPTIONS /api/users/users/ HTTP/1.1" 200 0
[13/Aug/2024 00:04:02] "GET /api/users/users/ HTTP/1.1" 200 1343
[13/Aug/2024 00:04:02] "GET /api/users/division-users/ HTTP/1.1" 200 95
[13/Aug/2024 00:04:02] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:04:02] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:04:02] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:04:02] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:05:53] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:05:53] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:05:53] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:05:53] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:05:57] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:05:57] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:05:57] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:05:57] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:07:15] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:07:15] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:07:23] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:07:23] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:07:38] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:07:38] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:07:40] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:07:40] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:07:40] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:07:40] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:07:49] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:07:49] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:07:49] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:07:49] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:07:58] "POST /api/token/ HTTP/1.1" 200 483
[13/Aug/2024 00:07:58] "GET /api/users/users/ HTTP/1.1" 200 1343
[13/Aug/2024 00:07:58] "GET /api/users/division-users/ HTTP/1.1" 200 95
[13/Aug/2024 00:07:58] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:07:58] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:07:58] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:07:58] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:09:01] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:09:01] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:09:02] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:09:02] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:09:04] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:09:04] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:09:10] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:09:10] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:09:10] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:09:10] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:09:11] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:09:11] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:09:11] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:09:11] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:09:21] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:09:21] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:09:21] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:09:21] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:09:24] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:09:24] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:09:24] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:09:24] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:09:26] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:09:26] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:09:26] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:09:26] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:09:38] "POST /api/token/ HTTP/1.1" 200 483
[13/Aug/2024 00:09:38] "GET /api/users/users/ HTTP/1.1" 200 1343
[13/Aug/2024 00:09:38] "GET /api/users/division-users/ HTTP/1.1" 200 95
[13/Aug/2024 00:09:38] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:09:38] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:09:38] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:09:38] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:09:40] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:09:40] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:09:40] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:09:40] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:12:02] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:12:02] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:12:02] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:12:02] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:12:06] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:12:06] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:12:06] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:12:06] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:12:56] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:12:56] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:12:56] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:12:56] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:12:57] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:12:57] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:12:57] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:12:57] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:14:25] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:14:25] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:14:25] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:14:25] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:14:29] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:14:29] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:14:29] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:14:29] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:16:15] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:16:15] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:16:15] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:16:15] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:16:18] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:16:18] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:16:18] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:16:18] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:16:32] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:16:32] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:16:32] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:16:32] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:16:33] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:16:33] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:16:33] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:16:33] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:18:05] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:18:05] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:18:07] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:18:07] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:18:07] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:18:07] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:18:11] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:18:11] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:18:11] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:18:11] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:18:11] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:18:11] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:18:11] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:18:12] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:18:15] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:18:15] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:18:21] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:18:21] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:18:44] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:18:44] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:18:46] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:18:46] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:18:51] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:18:51] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:21:48] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:21:48] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:21:53] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:21:53] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:21:53] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:21:53] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:00] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:00] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:00] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:00] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:10] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:10] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:11] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:11] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:14] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:14] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:17] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:17] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:17] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:17] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:20] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:20] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:20] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:20] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:20] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:20] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:20] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:20] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:21] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:21] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:21] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:21] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:22] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:22] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:22] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:22] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:23] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:23] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:23] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:23] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:26] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:26] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:26] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:26] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:30] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:30] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:30] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:30] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:40] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:40] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:40] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:40] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:44] "POST /api/token/ HTTP/1.1" 200 483
[13/Aug/2024 00:22:44] "GET /api/users/users/ HTTP/1.1" 200 1343
[13/Aug/2024 00:22:44] "OPTIONS /api/users/division-users/ HTTP/1.1" 200 0
[13/Aug/2024 00:22:44] "GET /api/users/division-users/ HTTP/1.1" 200 95
[13/Aug/2024 00:22:44] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:45] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:22:45] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:22:45] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:48:15] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:48:15] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:48:15] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:48:15] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:49:10] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:49:10] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:49:10] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:49:10] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:49:10] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:49:10] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:49:11] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:49:11] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:50:40] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:50:40] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:50:40] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:50:40] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:50:44] "POST /api/token/ HTTP/1.1" 200 483
[13/Aug/2024 00:50:44] "GET /api/users/users/ HTTP/1.1" 200 1343
[13/Aug/2024 00:50:44] "GET /api/users/division-users/ HTTP/1.1" 200 95
[13/Aug/2024 00:50:44] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:50:44] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:50:45] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:50:45] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:50:46] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:50:46] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:50:46] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:50:46] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:52:04] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:52:04] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:52:04] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:52:04] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:52:30] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:52:30] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:52:30] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:52:31] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:54:10] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:54:10] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:56:02] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:56:02] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:56:04] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:56:04] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:56:06] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:56:06] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:58:09] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:58:09] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:58:10] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:58:10] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 00:58:20] "POST /api/token/ HTTP/1.1" 200 483
[13/Aug/2024 00:58:20] "GET /api/users/users/ HTTP/1.1" 200 1343
[13/Aug/2024 00:58:20] "GET /api/users/division-users/ HTTP/1.1" 200 95
[13/Aug/2024 00:58:20] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 00:58:20] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:04:33] "POST /api/token/ HTTP/1.1" 200 483
[13/Aug/2024 01:04:33] "GET /api/users/users/ HTTP/1.1" 200 1343
[13/Aug/2024 01:04:33] "GET /api/users/division-users/ HTTP/1.1" 200 95
[13/Aug/2024 01:04:33] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:04:33] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:09:54] "OPTIONS /api/users/divisions/ HTTP/1.1" 200 0
[13/Aug/2024 01:09:54] "OPTIONS /api/users/division-users/?user=1 HTTP/1.1" 200 0
[13/Aug/2024 01:09:54] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:09:54] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:10:52] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:10:52] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:12:11] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:12:11] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:12:17] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:12:17] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:12:20] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:12:20] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:12:31] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:12:31] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:12:38] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:12:38] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:12:48] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:12:48] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:12:51] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:12:51] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:12:56] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:12:56] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:13:01] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:13:01] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:13:08] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:13:08] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:13:16] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:13:16] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:13:21] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:13:21] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:13:29] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:13:29] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:13:45] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:13:45] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:13:46] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:13:46] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:16:13] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:16:13] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:16:15] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:16:15] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:18:27] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:18:27] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:29:21] "POST /api/token/ HTTP/1.1" 200 483
[13/Aug/2024 01:29:21] "GET /api/users/users/ HTTP/1.1" 200 1343
[13/Aug/2024 01:29:21] "GET /api/users/division-users/ HTTP/1.1" 200 95
[13/Aug/2024 01:29:21] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:29:21] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:29:34] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:29:34] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:29:42] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:29:42] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:30:03] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:30:03] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:30:03] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:30:03] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:30:11] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:30:11] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:30:16] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:30:16] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:30:28] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:30:28] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:30:29] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:30:29] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:35:09] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:35:09] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:36:37] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:36:37] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:36:39] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:36:39] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:38:04] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:38:04] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 01:38:05] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 01:38:05] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
Not Found: /
[13/Aug/2024 03:58:49] "GET / HTTP/1.1" 404 3162
Not Found: /
[13/Aug/2024 03:59:46] "GET / HTTP/1.1" 404 3162
Not Found: /
[13/Aug/2024 04:04:38] "GET / HTTP/1.1" 404 3162
Not Found: /
[13/Aug/2024 04:17:04] "GET / HTTP/1.1" 404 3162
Not Found: /
[13/Aug/2024 13:10:24] "GET / HTTP/1.1" 404 3162
[13/Aug/2024 13:38:11] "OPTIONS /api/users/division-users/?user=1 HTTP/1.1" 200 0
[13/Aug/2024 13:38:11] "OPTIONS /api/users/divisions/ HTTP/1.1" 200 0
[13/Aug/2024 13:38:11] "OPTIONS /api/requests/requests/ HTTP/1.1" 200 0
[13/Aug/2024 13:38:11] "GET /api/requests/requests/ HTTP/1.1" 200 2
[13/Aug/2024 13:38:11] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 13:38:11] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 13:38:18] "OPTIONS /api/requests/companies/ HTTP/1.1" 200 0
[13/Aug/2024 13:38:18] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 13:38:18] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[13/Aug/2024 13:38:18] "GET /api/requests/companies/ HTTP/1.1" 200 352
[13/Aug/2024 13:38:22] "OPTIONS /api/requests/companies/1/ HTTP/1.1" 200 0
[13/Aug/2024 13:38:22] "PUT /api/requests/companies/1/ HTTP/1.1" 200 350
[13/Aug/2024 13:38:22] "GET /api/requests/companies/ HTTP/1.1" 200 352
[13/Aug/2024 13:38:25] "PUT /api/requests/companies/1/ HTTP/1.1" 200 352
[13/Aug/2024 13:38:25] "GET /api/requests/companies/ HTTP/1.1" 200 354
[13/Aug/2024 13:38:28] "PUT /api/requests/companies/1/ HTTP/1.1" 200 350
[13/Aug/2024 13:38:28] "GET /api/requests/companies/ HTTP/1.1" 200 352
Not Found: /
[13/Aug/2024 13:57:49] "GET / HTTP/1.1" 404 3162
[13/Aug/2024 15:01:19] "OPTIONS /api/token/ HTTP/1.1" 200 0
[13/Aug/2024 15:01:19] "POST /api/token/ HTTP/1.1" 200 483
[13/Aug/2024 15:01:19] "OPTIONS /api/users/users/ HTTP/1.1" 200 0
[13/Aug/2024 15:01:19] "GET /api/users/users/ HTTP/1.1" 200 1343
[13/Aug/2024 15:01:19] "OPTIONS /api/users/division-users/ HTTP/1.1" 200 0
[13/Aug/2024 15:01:19] "GET /api/users/division-users/ HTTP/1.1" 200 95
[13/Aug/2024 15:01:19] "GET /api/users/divisions/ HTTP/1.1" 200 55
[13/Aug/2024 15:01:19] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
Not Found: /
[13/Aug/2024 17:40:05] "GET / HTTP/1.1" 404 3162
Not Found: /
[13/Aug/2024 17:40:08] "GET / HTTP/1.1" 404 3162
Not Found: /
[13/Aug/2024 20:30:35] "GET / HTTP/1.1" 404 3162
Not Found: /
[14/Aug/2024 00:01:17] "GET / HTTP/1.1" 404 3162
Not Found: /
[14/Aug/2024 00:01:20] "GET /?fbclid=IwZXh0bgNhZW0CMTEAAR1Szfmd0q0CcAoFoUF8ffg_esamLEQWldmBfFJCGHR1ERTOGTgDhefOnAo_aem_X-KQ8uqnTx0MnnC5nFvTgw HTTP/1.1" 404 3274
Not Found: /
[14/Aug/2024 00:01:52] "GET / HTTP/1.1" 404 3162
Not Found: /
[14/Aug/2024 10:48:56] "GET / HTTP/1.1" 404 3162
Not Found: /.git/config
[14/Aug/2024 17:40:59] "GET /.git/config HTTP/1.1" 404 3213
Not Found: /.env
[14/Aug/2024 18:24:42] "GET /.env HTTP/1.1" 404 3192
Not Found: /.aws/credentials
[14/Aug/2024 18:24:42] "GET /.aws/credentials HTTP/1.1" 404 3228
Not Found: /api/.env
[14/Aug/2024 18:24:42] "GET /api/.env HTTP/1.1" 404 3204
Not Found: /.gitlab-ci.yml
[14/Aug/2024 18:24:42] "GET /.gitlab-ci.yml HTTP/1.1" 404 3222
Not Found: /
[14/Aug/2024 20:33:06] "GET / HTTP/1.1" 404 3162
Not Found: /
[14/Aug/2024 20:48:56] "GET / HTTP/1.1" 404 3162
Not Found: /
[14/Aug/2024 20:49:05] "GET / HTTP/1.1" 404 3162
Not Found: /
[15/Aug/2024 00:20:01] "GET / HTTP/1.1" 404 3162
Not Found: /
[15/Aug/2024 13:50:48] "GET / HTTP/1.1" 404 3162
Not Found: /
[15/Aug/2024 19:50:23] "GET / HTTP/1.1" 404 3162
Not Found: /
[15/Aug/2024 21:29:04] "GET / HTTP/1.1" 404 3162
Not Found: /
[16/Aug/2024 05:11:29] "GET / HTTP/1.1" 404 3162
Not Found: /
[16/Aug/2024 05:11:36] "GET / HTTP/1.1" 404 3162
Not Found: /
[16/Aug/2024 20:00:36] "GET / HTTP/1.1" 404 3162
Not Found: /
[17/Aug/2024 11:59:54] "GET / HTTP/1.1" 404 3162
Not Found: /
[17/Aug/2024 20:26:35] "GET / HTTP/1.1" 404 3162
Not Found: /
[18/Aug/2024 15:46:04] "GET / HTTP/1.1" 404 3162
Not Found: /
[18/Aug/2024 19:17:27] "GET / HTTP/1.1" 404 3162
Not Found: /
[19/Aug/2024 18:53:49] "GET / HTTP/1.1" 404 3162
Not Found: /.git/config
[20/Aug/2024 17:38:47] "GET /.git/config HTTP/1.1" 404 3213
Not Found: /
[21/Aug/2024 11:08:45] "GET / HTTP/1.1" 404 3162
Not Found: /
[22/Aug/2024 20:19:33] "GET / HTTP/1.1" 404 3162
Not Found: /.git/config
[26/Aug/2024 16:43:28] "GET /.git/config HTTP/1.1" 404 3213
Not Found: /
[29/Aug/2024 23:28:54] "GET / HTTP/1.1" 404 3162
Not Found: /
[02/Sep/2024 15:01:28] "GET / HTTP/1.1" 404 3162
Not Found: /
[03/Sep/2024 11:47:28] "GET / HTTP/1.1" 404 3162
Not Found: /
[04/Sep/2024 10:13:55] "GET / HTTP/1.1" 404 3162
Not Found: /
[04/Sep/2024 12:39:28] "GET / HTTP/1.1" 404 3162
Not Found: /
[06/Sep/2024 11:49:06] "GET / HTTP/1.1" 404 3162
Not Found: /.git/config
[08/Sep/2024 11:44:09] "GET /.git/config HTTP/1.1" 404 3213
Not Found: /
[11/Sep/2024 18:17:52] "GET / HTTP/1.1" 404 3162
Not Found: /
[12/Sep/2024 21:55:17] "GET / HTTP/1.1" 404 3162
Not Found: /
[18/Sep/2024 09:51:55] "GET / HTTP/1.1" 404 3162
Not Found: /
[18/Sep/2024 23:34:37] "GET / HTTP/1.1" 404 3162
Not Found: /
[26/Sep/2024 15:42:52] "GET / HTTP/1.1" 404 3162
Not Found: /
[27/Sep/2024 07:17:05] "GET / HTTP/1.1" 404 3162
Not Found: /
[05/Oct/2024 17:09:37] "GET / HTTP/1.1" 404 3162
Not Found: /
[07/Oct/2024 10:35:47] "GET / HTTP/1.1" 404 3162
[08/Oct/2024 01:47:05] "OPTIONS /api/token/ HTTP/1.1" 200 0
[08/Oct/2024 01:47:05] "OPTIONS /api/token/ HTTP/1.1" 200 0
Unauthorized: /api/token/
Unauthorized: /api/token/
[08/Oct/2024 01:47:06] "POST /api/token/ HTTP/1.1" 401 63
[08/Oct/2024 01:47:06] "POST /api/token/ HTTP/1.1" 401 63
[08/Oct/2024 01:47:08] "POST /api/token/ HTTP/1.1" 200 483
[08/Oct/2024 01:47:08] "OPTIONS /api/users/users/ HTTP/1.1" 200 0
[08/Oct/2024 01:47:08] "GET /api/users/users/ HTTP/1.1" 200 1343
[08/Oct/2024 01:47:08] "OPTIONS /api/users/division-users/ HTTP/1.1" 200 0
[08/Oct/2024 01:47:08] "GET /api/users/division-users/ HTTP/1.1" 200 95
[08/Oct/2024 01:47:08] "OPTIONS /api/users/divisions/ HTTP/1.1" 200 0
[08/Oct/2024 01:47:08] "OPTIONS /api/users/division-users/?user=1 HTTP/1.1" 200 0
[08/Oct/2024 01:47:08] "GET /api/users/divisions/ HTTP/1.1" 200 55
[08/Oct/2024 01:47:08] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
Not Found: /api/
[08/Oct/2024 01:53:07] "GET /api/ HTTP/1.1" 404 3192
[08/Oct/2024 01:53:13] "GET /api/users/users/ HTTP/1.1" 200 8089
[08/Oct/2024 01:55:16] "POST /api/token/ HTTP/1.1" 200 483
[08/Oct/2024 01:55:16] "GET /api/users/users/ HTTP/1.1" 200 1343
[08/Oct/2024 01:55:16] "GET /api/users/division-users/ HTTP/1.1" 200 95
[08/Oct/2024 01:55:16] "GET /api/users/divisions/ HTTP/1.1" 200 55
[08/Oct/2024 01:55:16] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[08/Oct/2024 11:11:58] "OPTIONS /api/token/ HTTP/1.1" 200 0
[08/Oct/2024 11:11:58] "OPTIONS /api/token/ HTTP/1.1" 200 0
Unauthorized: /api/token/
Unauthorized: /api/token/
[08/Oct/2024 11:11:59] "POST /api/token/ HTTP/1.1" 401 63
[08/Oct/2024 11:11:59] "POST /api/token/ HTTP/1.1" 401 63
[08/Oct/2024 11:12:01] "POST /api/token/ HTTP/1.1" 200 483
[08/Oct/2024 11:12:01] "OPTIONS /api/users/users/ HTTP/1.1" 200 0
[08/Oct/2024 11:12:01] "GET /api/users/users/ HTTP/1.1" 200 1343
[08/Oct/2024 11:12:01] "OPTIONS /api/users/division-users/ HTTP/1.1" 200 0
[08/Oct/2024 11:12:01] "GET /api/users/division-users/ HTTP/1.1" 200 95
[08/Oct/2024 11:12:01] "OPTIONS /api/users/divisions/ HTTP/1.1" 200 0
[08/Oct/2024 11:12:01] "OPTIONS /api/users/division-users/?user=1 HTTP/1.1" 200 0
[08/Oct/2024 11:12:01] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[08/Oct/2024 11:12:01] "GET /api/users/divisions/ HTTP/1.1" 200 55
[08/Oct/2024 17:23:35] "OPTIONS /api/token/ HTTP/1.1" 200 0
[08/Oct/2024 17:23:35] "OPTIONS /api/token/ HTTP/1.1" 200 0
Unauthorized: /api/token/
Unauthorized: /api/token/
[08/Oct/2024 17:23:36] "POST /api/token/ HTTP/1.1" 401 63
[08/Oct/2024 17:23:36] "POST /api/token/ HTTP/1.1" 401 63
Unauthorized: /api/token/
[08/Oct/2024 17:23:41] "POST /api/token/ HTTP/1.1" 401 63
[08/Oct/2024 17:24:03] "POST /api/token/ HTTP/1.1" 200 483
[08/Oct/2024 17:24:03] "OPTIONS /api/users/users/ HTTP/1.1" 200 0
[08/Oct/2024 17:24:03] "GET /api/users/users/ HTTP/1.1" 200 1343
[08/Oct/2024 17:24:03] "OPTIONS /api/users/division-users/ HTTP/1.1" 200 0
[08/Oct/2024 17:24:03] "GET /api/users/division-users/ HTTP/1.1" 200 95
[08/Oct/2024 17:24:04] "OPTIONS /api/users/divisions/ HTTP/1.1" 200 0
[08/Oct/2024 17:24:04] "OPTIONS /api/users/division-users/?user=1 HTTP/1.1" 200 0
[08/Oct/2024 17:24:04] "GET /api/users/divisions/ HTTP/1.1" 200 55
[08/Oct/2024 17:24:04] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
Unauthorized: /api/token/
[08/Oct/2024 18:59:43] "POST /api/token/ HTTP/1.1" 401 63
Unauthorized: /api/token/
[08/Oct/2024 18:59:43] "POST /api/token/ HTTP/1.1" 401 63
[08/Oct/2024 18:59:52] "POST /api/token/ HTTP/1.1" 200 483
[08/Oct/2024 18:59:52] "GET /api/users/users/ HTTP/1.1" 200 1343
[08/Oct/2024 18:59:52] "GET /api/users/division-users/ HTTP/1.1" 200 95
[08/Oct/2024 18:59:52] "GET /api/users/divisions/ HTTP/1.1" 200 55
[08/Oct/2024 18:59:52] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[08/Oct/2024 19:12:58] "POST /api/token/ HTTP/1.1" 200 483
[08/Oct/2024 19:12:58] "GET /api/users/users/ HTTP/1.1" 200 1343
[08/Oct/2024 19:12:58] "GET /api/users/division-users/ HTTP/1.1" 200 95
[08/Oct/2024 19:12:58] "GET /api/users/divisions/ HTTP/1.1" 200 55
[08/Oct/2024 19:12:58] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[08/Oct/2024 19:32:53] "OPTIONS /api/token/ HTTP/1.1" 200 0
[08/Oct/2024 19:32:53] "OPTIONS /api/token/ HTTP/1.1" 200 0
Unauthorized: /api/token/
Unauthorized: /api/token/
[08/Oct/2024 19:32:54] "POST /api/token/ HTTP/1.1" 401 63
[08/Oct/2024 19:32:54] "POST /api/token/ HTTP/1.1" 401 63
[08/Oct/2024 20:58:35] "POST /api/token/ HTTP/1.1" 200 483
[08/Oct/2024 20:58:35] "OPTIONS /api/users/users/ HTTP/1.1" 200 0
[08/Oct/2024 20:58:35] "GET /api/users/users/ HTTP/1.1" 200 1343
[08/Oct/2024 20:58:35] "OPTIONS /api/users/division-users/ HTTP/1.1" 200 0
[08/Oct/2024 20:58:35] "GET /api/users/division-users/ HTTP/1.1" 200 95
[08/Oct/2024 20:58:35] "OPTIONS /api/users/divisions/ HTTP/1.1" 200 0
[08/Oct/2024 20:58:35] "OPTIONS /api/users/division-users/?user=1 HTTP/1.1" 200 0
[08/Oct/2024 20:58:35] "GET /api/users/divisions/ HTTP/1.1" 200 55
[08/Oct/2024 20:58:35] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[08/Oct/2024 21:02:20] "GET /api/requests/requests/ HTTP/1.1" 200 5460
[08/Oct/2024 21:03:39] "GET /api-auth/login/?next=/api/requests/requests/ HTTP/1.1" 200 2740
[08/Oct/2024 21:03:47] "POST /api-auth/login/ HTTP/1.1" 302 0
[08/Oct/2024 21:03:47] "GET /api/requests/requests/ HTTP/1.1" 200 13164
[08/Oct/2024 21:07:02] "POST /api/requests/requests/ HTTP/1.1" 201 14000
[09/Oct/2024 10:53:38] "GET /api/users/users/ HTTP/1.1" 200 8129
[09/Oct/2024 13:45:31] "OPTIONS /api/token/ HTTP/1.1" 200 0
[09/Oct/2024 13:45:31] "OPTIONS /api/token/ HTTP/1.1" 200 0
Unauthorized: /api/token/
Unauthorized: /api/token/
[09/Oct/2024 13:45:31] "POST /api/token/ HTTP/1.1" 401 63
[09/Oct/2024 13:45:31] "POST /api/token/ HTTP/1.1" 401 63
[09/Oct/2024 13:45:33] "POST /api/token/ HTTP/1.1" 200 483
[09/Oct/2024 13:45:33] "OPTIONS /api/users/users/ HTTP/1.1" 200 0
[09/Oct/2024 13:45:33] "GET /api/users/users/ HTTP/1.1" 200 1373
[09/Oct/2024 13:45:33] "OPTIONS /api/users/division-users/ HTTP/1.1" 200 0
[09/Oct/2024 13:45:33] "GET /api/users/division-users/ HTTP/1.1" 200 95
[09/Oct/2024 13:45:33] "OPTIONS /api/users/divisions/ HTTP/1.1" 200 0
[09/Oct/2024 13:45:33] "OPTIONS /api/users/division-users/?user=1 HTTP/1.1" 200 0
[09/Oct/2024 13:45:33] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 13:45:34] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:10:05] "OPTIONS /api/requests/requests/ HTTP/1.1" 200 0
[09/Oct/2024 14:10:05] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:10:05] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:10:05] "GET /api/requests/requests/ HTTP/1.1" 200 382
[09/Oct/2024 14:10:17] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:10:17] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:10:48] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:10:48] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:10:51] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:10:51] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:11:05] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:11:05] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:11:05] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:11:05] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:11:06] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:11:06] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:11:06] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:11:06] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:11:06] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:11:06] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:11:06] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:11:06] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:11:06] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:11:06] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:11:07] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:11:07] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:11:07] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:11:07] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:11:07] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:11:07] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:11:27] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:11:27] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:11:28] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:11:28] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:11:28] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:11:28] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:11:30] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:11:30] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:26:27] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:26:27] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:26:28] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:26:28] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:26:30] "GET /api/requests/requests/ HTTP/1.1" 200 382
[09/Oct/2024 14:26:34] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:26:34] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:26:56] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:26:56] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:26:58] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:26:58] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:26:59] "GET /api/requests/requests/ HTTP/1.1" 200 382
[09/Oct/2024 14:27:01] "GET /api/requests/requests/ HTTP/1.1" 200 382
[09/Oct/2024 14:27:49] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:27:49] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:27:50] "GET /api/requests/requests/ HTTP/1.1" 200 382
[09/Oct/2024 14:27:52] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:27:52] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:27:52] "GET /api/requests/requests/ HTTP/1.1" 200 382
[09/Oct/2024 14:28:04] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:28:04] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:28:06] "GET /api/requests/requests/ HTTP/1.1" 200 382
[09/Oct/2024 14:30:25] "GET /api/requests/requests/ HTTP/1.1" 200 382
[09/Oct/2024 14:30:25] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:30:25] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:31:16] "GET /api/requests/requests/ HTTP/1.1" 200 382
[09/Oct/2024 14:31:54] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:31:54] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:31:55] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:31:55] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:32:01] "GET /api/requests/requests/ HTTP/1.1" 200 382
[09/Oct/2024 14:32:04] "GET /api/requests/requests/ HTTP/1.1" 200 382
[09/Oct/2024 14:35:17] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:35:17] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:35:44] "GET /api/requests/requests/ HTTP/1.1" 200 382
[09/Oct/2024 14:35:59] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:35:59] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:36:04] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:36:04] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:37:29] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:37:29] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:38:45] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:38:45] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:39:02] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:39:02] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:39:18] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:39:18] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:39:25] "GET /api/requests/requests/ HTTP/1.1" 200 382
[09/Oct/2024 14:39:56] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:39:56] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:40:03] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:40:03] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:40:14] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:40:14] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:40:19] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:40:19] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:40:54] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:40:54] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:40:57] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:40:57] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:41:14] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:41:14] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:42:17] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:42:17] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:42:47] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:42:47] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:42:54] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:42:54] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:43:39] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:43:39] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:44:03] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:44:03] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:44:04] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:44:04] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:44:24] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:44:24] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:44:52] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:44:52] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:44:54] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:44:54] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:46:16] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:46:16] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:46:42] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:46:42] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:46:44] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:46:44] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:46:48] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:46:48] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:46:52] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:46:52] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:46:55] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:46:55] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:46:56] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:46:56] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:47:15] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:47:15] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:47:18] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:47:18] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:49:41] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:49:41] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:49:49] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:49:49] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:49:50] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:49:50] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:51:33] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:51:33] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:51:35] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:51:35] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:52:22] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:52:22] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:53:09] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:53:09] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:53:19] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 14:53:19] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:56:09] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 14:56:09] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:06:40] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:06:40] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 15:06:41] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:06:41] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 15:06:45] "GET /api/requests/requests/ HTTP/1.1" 200 382
[09/Oct/2024 15:07:16] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:07:16] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 15:07:31] "POST /api/token/ HTTP/1.1" 200 483
[09/Oct/2024 15:07:31] "GET /api/users/users/ HTTP/1.1" 200 1373
[09/Oct/2024 15:07:31] "GET /api/users/division-users/ HTTP/1.1" 200 95
[09/Oct/2024 15:07:31] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 15:07:31] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:08:12] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 15:08:12] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:08:13] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:08:13] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 15:08:16] "GET /api/requests/requests/ HTTP/1.1" 200 382
[09/Oct/2024 15:08:20] "POST /api/token/ HTTP/1.1" 200 483
[09/Oct/2024 15:08:20] "GET /api/users/users/ HTTP/1.1" 200 1373
[09/Oct/2024 15:08:20] "GET /api/users/division-users/ HTTP/1.1" 200 95
[09/Oct/2024 15:08:20] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:08:22] "OPTIONS /api/users/users/1/ HTTP/1.1" 200 0
[09/Oct/2024 15:08:22] "GET /api/users/users/1/ HTTP/1.1" 200 461
[09/Oct/2024 15:08:43] "POST /api/token/ HTTP/1.1" 200 483
[09/Oct/2024 15:08:43] "GET /api/users/users/ HTTP/1.1" 200 1373
[09/Oct/2024 15:08:43] "GET /api/users/division-users/ HTTP/1.1" 200 95
[09/Oct/2024 15:08:43] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:09:23] "POST /api/token/ HTTP/1.1" 200 483
[09/Oct/2024 15:09:23] "GET /api/users/users/ HTTP/1.1" 200 1373
[09/Oct/2024 15:09:23] "GET /api/users/division-users/ HTTP/1.1" 200 95
[09/Oct/2024 15:09:23] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:09:23] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 15:09:25] "GET /api/users/users/1/ HTTP/1.1" 200 461
[09/Oct/2024 15:09:37] "OPTIONS /api/users/users/undefined/ HTTP/1.1" 200 0
Not Found: /api/users/users/undefined/
[09/Oct/2024 15:09:37] "PUT /api/users/users/undefined/ HTTP/1.1" 404 23
[09/Oct/2024 15:09:43] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:09:43] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 15:09:43] "GET /api/users/users/1/ HTTP/1.1" 200 461
Not Found: /api/users/users/undefined/
[09/Oct/2024 15:10:05] "PUT /api/users/users/undefined/ HTTP/1.1" 404 23
Not Found: /api/users/users/undefined/
[09/Oct/2024 15:10:16] "PUT /api/users/users/undefined/ HTTP/1.1" 404 23
Not Found: /api/users/users/undefined/
[09/Oct/2024 15:10:20] "GET /api/users/users/undefined/ HTTP/1.1" 404 5671
[09/Oct/2024 15:11:28] "GET /api/users/users/ HTTP/1.1" 200 8129
[09/Oct/2024 15:12:13] "GET /api/users/users/1/ HTTP/1.1" 200 461
[09/Oct/2024 15:12:16] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:12:16] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 15:12:16] "GET /api/users/users/1/ HTTP/1.1" 200 461
Bad Request: /api/users/users/1/
[09/Oct/2024 15:12:18] "PUT /api/users/users/1/ HTTP/1.1" 400 40
[09/Oct/2024 15:12:25] "GET /api/users/users/1/ HTTP/1.1" 200 6415
Bad Request: /api/users/users/1/
[09/Oct/2024 15:12:28] "PUT /api/users/users/1/ HTTP/1.1" 400 40
[09/Oct/2024 15:13:25] "GET /api/users/users/1/ HTTP/1.1" 200 461
[09/Oct/2024 15:13:26] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:13:26] "GET /api/users/users/1/ HTTP/1.1" 200 461
[09/Oct/2024 15:13:26] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
Bad Request: /api/users/users/1/
[09/Oct/2024 15:13:28] "PUT /api/users/users/1/ HTTP/1.1" 400 40
[09/Oct/2024 15:14:56] "GET /api/users/users/1/ HTTP/1.1" 200 461
[09/Oct/2024 15:15:03] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:15:03] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 15:15:03] "GET /api/users/users/1/ HTTP/1.1" 200 461
Bad Request: /api/users/users/1/
[09/Oct/2024 15:15:06] "PUT /api/users/users/1/ HTTP/1.1" 400 40
[09/Oct/2024 15:15:20] "GET /api-auth/login/?next=/api/users/users/ HTTP/1.1" 200 2734
[09/Oct/2024 15:15:22] "POST /api-auth/login/ HTTP/1.1" 302 0
[09/Oct/2024 15:15:22] "GET /api/users/users/ HTTP/1.1" 200 22113
[09/Oct/2024 15:16:08] "GET /api/users/users/1/ HTTP/1.1" 200 461
[09/Oct/2024 15:16:09] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:16:09] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 15:16:09] "GET /api/users/users/1/ HTTP/1.1" 200 461
Bad Request: /api/users/users/1/
[09/Oct/2024 15:16:11] "PUT /api/users/users/1/ HTTP/1.1" 400 40
Bad Request: /api/users/users/1/
[09/Oct/2024 15:16:31] "PUT /api/users/users/1/ HTTP/1.1" 400 40
[09/Oct/2024 15:17:25] "GET /api/users/users/1/ HTTP/1.1" 200 461
[09/Oct/2024 15:17:38] "GET /api/users/users/1/ HTTP/1.1" 200 461
[09/Oct/2024 15:17:39] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:17:39] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 15:17:39] "GET /api/users/users/1/ HTTP/1.1" 200 461
[09/Oct/2024 15:17:44] "PATCH /api/users/users/1/ HTTP/1.1" 200 461
[09/Oct/2024 15:17:44] "GET /api/users/users/1/ HTTP/1.1" 200 461
[09/Oct/2024 15:17:47] "PATCH /api/users/users/1/ HTTP/1.1" 200 463
[09/Oct/2024 15:17:47] "GET /api/users/users/1/ HTTP/1.1" 200 463
[09/Oct/2024 15:17:49] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:17:49] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 15:17:49] "GET /api/users/users/1/ HTTP/1.1" 200 463
[09/Oct/2024 15:17:57] "GET /api-auth/login/?next=/api/users/users/ HTTP/1.1" 200 2734
[09/Oct/2024 15:18:00] "GET /api/users/users/ HTTP/1.1" 200 22117
[09/Oct/2024 15:18:13] "PATCH /api/users/users/1/ HTTP/1.1" 200 471
[09/Oct/2024 15:18:13] "GET /api/users/users/1/ HTTP/1.1" 200 471
[09/Oct/2024 15:18:21] "GET /api/users/users/1/ HTTP/1.1" 200 471
[09/Oct/2024 15:18:25] "GET /api/users/users/1/ HTTP/1.1" 200 471
[09/Oct/2024 15:18:43] "GET /api/users/users/1/ HTTP/1.1" 200 471
[09/Oct/2024 15:18:46] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:18:46] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 15:18:46] "GET /api/users/users/1/ HTTP/1.1" 200 471
[09/Oct/2024 15:18:54] "GET /api/users/users/ HTTP/1.1" 200 22123
[09/Oct/2024 15:18:58] "PATCH /api/users/users/1/ HTTP/1.1" 200 476
[09/Oct/2024 15:18:58] "GET /api/users/users/1/ HTTP/1.1" 200 476
[09/Oct/2024 15:19:12] "GET /api/users/users/1/ HTTP/1.1" 200 476
[09/Oct/2024 15:19:12] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:19:12] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 15:19:12] "GET /api/users/users/1/ HTTP/1.1" 200 476
[09/Oct/2024 15:19:15] "GET /api/users/users/1/ HTTP/1.1" 200 476
[09/Oct/2024 15:19:18] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:19:18] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 15:19:18] "GET /api/users/users/1/ HTTP/1.1" 200 476
[09/Oct/2024 15:19:26] "GET /api/users/users/1/ HTTP/1.1" 200 476
[09/Oct/2024 15:19:27] "GET /api/users/divisions/ HTTP/1.1" 200 55
[09/Oct/2024 15:19:27] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[09/Oct/2024 15:19:27] "GET /api/users/users/1/ HTTP/1.1" 200 476
[09/Oct/2024 15:22:39] "GET /api/requests/requests/ HTTP/1.1" 200 382
[09/Oct/2024 15:22:41] "GET /api/requests/requests/ HTTP/1.1" 200 382
[09/Oct/2024 15:23:45] "GET /api/users/users/ HTTP/1.1" 200 22133
[09/Oct/2024 15:23:46] "GET /api/users/users/ HTTP/1.1" 200 22133
[09/Oct/2024 15:23:47] "GET /api/users/users/ HTTP/1.1" 200 22133
[10/Oct/2024 00:45:52] "OPTIONS /api/token/ HTTP/1.1" 200 0
[10/Oct/2024 00:45:52] "OPTIONS /api/token/ HTTP/1.1" 200 0
Unauthorized: /api/token/
[10/Oct/2024 00:45:53] "POST /api/token/ HTTP/1.1" 401 63
Unauthorized: /api/token/
[10/Oct/2024 00:45:53] "POST /api/token/ HTTP/1.1" 401 63
[10/Oct/2024 00:45:56] "POST /api/token/ HTTP/1.1" 200 483
[10/Oct/2024 00:45:56] "OPTIONS /api/users/users/ HTTP/1.1" 200 0
[10/Oct/2024 00:45:57] "GET /api/users/users/ HTTP/1.1" 200 1388
[10/Oct/2024 00:45:57] "OPTIONS /api/users/division-users/ HTTP/1.1" 200 0
[10/Oct/2024 00:45:57] "GET /api/users/division-users/ HTTP/1.1" 200 95
[10/Oct/2024 00:45:58] "OPTIONS /api/users/divisions/ HTTP/1.1" 200 0
[10/Oct/2024 00:45:58] "OPTIONS /api/users/division-users/?user=1 HTTP/1.1" 200 0
[10/Oct/2024 00:45:58] "GET /api/users/divisions/ HTTP/1.1" 200 55
[10/Oct/2024 00:45:58] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[10/Oct/2024 00:46:04] "POST /api/token/ HTTP/1.1" 200 483
[10/Oct/2024 00:46:04] "GET /api/users/users/ HTTP/1.1" 200 1388
[10/Oct/2024 00:46:05] "GET /api/users/division-users/ HTTP/1.1" 200 95
[10/Oct/2024 00:46:05] "GET /api/users/divisions/ HTTP/1.1" 200 55
[10/Oct/2024 00:46:05] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[10/Oct/2024 00:46:14] "OPTIONS /api/requests/requests/ HTTP/1.1" 200 0
[10/Oct/2024 00:46:14] "GET /api/requests/requests/ HTTP/1.1" 200 382
[10/Oct/2024 09:27:45] "OPTIONS /api/users/division-users/?user=1 HTTP/1.1" 200 0
[10/Oct/2024 09:27:45] "OPTIONS /api/users/divisions/ HTTP/1.1" 200 0
[10/Oct/2024 09:27:45] "OPTIONS /api/requests/requests/ HTTP/1.1" 200 0
[10/Oct/2024 09:27:45] "GET /api/users/divisions/ HTTP/1.1" 200 55
[10/Oct/2024 09:27:45] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[10/Oct/2024 09:27:45] "GET /api/requests/requests/ HTTP/1.1" 200 382
[10/Oct/2024 09:28:23] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[10/Oct/2024 09:28:23] "GET /api/users/divisions/ HTTP/1.1" 200 55
[10/Oct/2024 09:28:23] "GET /api/requests/requests/ HTTP/1.1" 200 382
[10/Oct/2024 09:49:04] "GET /api/users/users/1/ HTTP/1.1" 200 22125
[10/Oct/2024 09:54:47] "GET /api/users/divisions/ HTTP/1.1" 200 55
[10/Oct/2024 09:54:47] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[10/Oct/2024 09:54:49] "OPTIONS /api/users/users/1/ HTTP/1.1" 200 0
[10/Oct/2024 09:54:49] "GET /api/users/users/1/ HTTP/1.1" 200 476
[10/Oct/2024 09:54:57] "GET /api/requests/requests/ HTTP/1.1" 200 382
[10/Oct/2024 10:06:32] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[10/Oct/2024 10:06:32] "GET /api/users/divisions/ HTTP/1.1" 200 55
[10/Oct/2024 10:06:32] "GET /api/requests/requests/ HTTP/1.1" 200 382
[10/Oct/2024 10:06:35] "OPTIONS /api/requests/companies/ HTTP/1.1" 200 0
[10/Oct/2024 10:06:35] "GET /api/users/divisions/ HTTP/1.1" 200 55
[10/Oct/2024 10:06:35] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[10/Oct/2024 10:06:35] "GET /api/requests/companies/ HTTP/1.1" 200 352
[10/Oct/2024 10:09:01] "GET /api/requests/requests/ HTTP/1.1" 200 382
[10/Oct/2024 10:09:01] "GET /api/requests/requests/ HTTP/1.1" 200 382
[10/Oct/2024 10:09:08] "GET /api/users/divisions/ HTTP/1.1" 200 55
[10/Oct/2024 10:09:08] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[10/Oct/2024 10:09:08] "GET /api/requests/requests/ HTTP/1.1" 200 382
[10/Oct/2024 10:15:52] "GET /api/users/divisions/ HTTP/1.1" 200 55
[10/Oct/2024 10:15:52] "GET /api/requests/companies/ HTTP/1.1" 200 352
[10/Oct/2024 10:15:52] "GET /api/users/division-users/?user=1 HTTP/1.1" 200 95
[10/Oct/2024 10:16:10] "GET /api/requests/ HTTP/1.1" 200 6219
[10/Oct/2024 10:16:11] "GET /api/requests/requests/ HTTP/1.1" 200 13905
[10/Oct/2024 10:16:24] "GET /api/requests/companies/ HTTP/1.1" 200 13966
[10/Oct/2024 10:17:08] "GET /api/users/ HTTP/1.1" 200 6566
[10/Oct/2024 10:17:10] "GET /api/users/users/ HTTP/1.1" 200 22133
/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
August 12, 2024 - 22:06:40
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 126, in inner_run
    autoreload.raise_last_exception()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py", line 31, in <module>
    class User(AbstractBaseUser, PermissionsMixin):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py", line 44, in User
    company = models.ForeignKey(Company, null=True, blank=True, on_delete=models.SET_NULL)
NameError: name 'Company' is not defined
/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 126, in inner_run
    autoreload.raise_last_exception()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py", line 4, in <module>
    from Requests.models import Company 
ModuleNotFoundError: No module named 'Requests'
/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/base.py", line 563, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
requests.Company.responsible: (fields.E303) Reverse query name for 'requests.Company.responsible' clashes with field name 'users.User.company'.
	HINT: Rename field 'users.User.company', or add/change a related_name argument to the definition for field 'requests.Company.responsible'.

System check identified 1 issue (0 silenced).
/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/base.py", line 563, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
requests.Company.responsible: (fields.E303) Reverse query name for 'requests.Company.responsible' clashes with field name 'users.User.company'.
	HINT: Rename field 'users.User.company', or add/change a related_name argument to the definition for field 'requests.Company.responsible'.

System check identified 1 issue (0 silenced).
/home/czebravisualdata-api/htdocs/CzebraVisual/czebra/settings.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/apps/config.py", line 210, in create
    app_module = import_module(app_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 126, in inner_run
    autoreload.raise_last_exception()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/apps/config.py", line 212, in create
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Cannot import 'users'. Check that 'Users.apps.UsersConfig.name' is correct.
/home/czebravisualdata-api/htdocs/CzebraVisual/czebra/settings.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 126, in inner_run
    autoreload.raise_last_exception()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py", line 4, in <module>
    from Requests.models import Company
ModuleNotFoundError: No module named 'Requests'
/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/base.py", line 563, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
requests.Company.responsible: (fields.E303) Reverse query name for 'requests.Company.responsible' clashes with field name 'users.User.company'.
	HINT: Rename field 'users.User.company', or add/change a related_name argument to the definition for field 'requests.Company.responsible'.

System check identified 1 issue (0 silenced).
/home/czebravisualdata-api/htdocs/CzebraVisual/requests/models.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 10, 2024 - 10:42:54
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 10, 2024 - 10:43:27
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 126, in inner_run
    autoreload.raise_last_exception()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py", line 32, in <module>
    class User(AbstractBaseUser, PermissionsMixin):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py", line 39, in User
    code = models.CharField(max_length=20, unique=True, default=uuid.uuid4, null=False)
NameError: name 'uuid' is not defined
/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py changed, reloading.
Watching for file changes with StatReloader
/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): users.
Run 'python manage.py migrate' to apply them.
October 10, 2024 - 10:47:48
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/home/czebravisualdata-api/htdocs/CzebraVisual/requests/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): users.
Run 'python manage.py migrate' to apply them.
October 10, 2024 - 10:47:49
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 187, in check_key
    return self.graph.root_nodes(key[0])[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
    self.check_migrations()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/base.py", line 581, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 250, in build_graph
    self.add_external_dependencies(key, migration)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 214, in add_external_dependencies
    parent = self.check_key(parent, key[0])
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 194, in check_key
    raise ValueError(
ValueError: Dependency on app with no migrations: users
/home/czebravisualdata-api/htdocs/CzebraVisual/requests/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 187, in check_key
    return self.graph.root_nodes(key[0])[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
    self.check_migrations()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/base.py", line 581, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 250, in build_graph
    self.add_external_dependencies(key, migration)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 214, in add_external_dependencies
    parent = self.check_key(parent, key[0])
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 194, in check_key
    raise ValueError(
ValueError: Dependency on app with no migrations: users
/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 531, in check
    for pattern in self.url_patterns:
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 718, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 711, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/czebra/urls.py", line 15, in <module>
    path('api/users/', include('users.urls')),
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/users/urls.py", line 3, in <module>
    from .views import UserViewSet, NotificationViewSet, DivisionViewSet, DivisionUserViewSet
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/users/views.py", line 2, in <module>
    from .models import User, Notification, Division, DivisionUser
ImportError: cannot import name 'Division' from 'users.models' (/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py)
/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 531, in check
    for pattern in self.url_patterns:
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 718, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 711, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/czebra/urls.py", line 15, in <module>
    path('api/users/', include('users.urls')),
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/users/urls.py", line 3, in <module>
    from .views import UserViewSet, NotificationViewSet, DivisionViewSet, DivisionUserViewSet
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/users/views.py", line 2, in <module>
    from .models import User, Notification, Division, DivisionUser
ImportError: cannot import name 'Notification' from 'users.models' (/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py)
/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 187, in check_key
    return self.graph.root_nodes(key[0])[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
    self.check_migrations()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/base.py", line 581, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 250, in build_graph
    self.add_external_dependencies(key, migration)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 214, in add_external_dependencies
    parent = self.check_key(parent, key[0])
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 194, in check_key
    raise ValueError(
ValueError: Dependency on app with no migrations: users
/home/czebravisualdata-api/htdocs/CzebraVisual/requests/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
Watching for file changes with StatReloader
Internal Server Error: /api/users/
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column users_user.code does not exist
LINE 1: ...ers_user"."is_superuser", "users_user"."user_id", "users_use...
                                                             ^
HINT:  Perhaps you meant to reference the column "users_user.role".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/authentication.py", line 127, in authenticate
    if not user or not user.is_active:
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/contrib/auth/middleware.py", line 37, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/contrib/auth/middleware.py", line 17, in get_user
    request._cached_user = auth.get_user(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/contrib/auth/__init__.py", line 216, in get_user
    user = backend.get_user(user_id)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/contrib/auth/backends.py", line 157, in get_user
    user = UserModel._default_manager.get(pk=user_id)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column users_user.code does not exist
LINE 1: ...ers_user"."is_superuser", "users_user"."user_id", "users_use...
                                                             ^
HINT:  Perhaps you meant to reference the column "users_user.role".

[10/Oct/2024 12:07:32] "GET /api/users/ HTTP/1.1" 500 203425
/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 10, 2024 - 12:04:05
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Internal Server Error: /api/users/
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column users_user.code does not exist
LINE 1: ...ers_user"."is_superuser", "users_user"."user_id", "users_use...
                                                             ^
HINT:  Perhaps you meant to reference the column "users_user.role".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/authentication.py", line 127, in authenticate
    if not user or not user.is_active:
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/contrib/auth/middleware.py", line 37, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/contrib/auth/middleware.py", line 17, in get_user
    request._cached_user = auth.get_user(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/contrib/auth/__init__.py", line 216, in get_user
    user = backend.get_user(user_id)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/contrib/auth/backends.py", line 157, in get_user
    user = UserModel._default_manager.get(pk=user_id)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column users_user.code does not exist
LINE 1: ...ers_user"."is_superuser", "users_user"."user_id", "users_use...
                                                             ^
HINT:  Perhaps you meant to reference the column "users_user.role".

[10/Oct/2024 12:09:22] "GET /api/users/ HTTP/1.1" 500 203562
Internal Server Error: /api/users/
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column users_user.code does not exist
LINE 1: ...ers_user"."is_superuser", "users_user"."user_id", "users_use...
                                                             ^
HINT:  Perhaps you meant to reference the column "users_user.role".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/authentication.py", line 127, in authenticate
    if not user or not user.is_active:
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/contrib/auth/middleware.py", line 37, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/contrib/auth/middleware.py", line 17, in get_user
    request._cached_user = auth.get_user(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/contrib/auth/__init__.py", line 216, in get_user
    user = backend.get_user(user_id)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/contrib/auth/backends.py", line 157, in get_user
    user = UserModel._default_manager.get(pk=user_id)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column users_user.code does not exist
LINE 1: ...ers_user"."is_superuser", "users_user"."user_id", "users_use...
                                                             ^
HINT:  Perhaps you meant to reference the column "users_user.role".

[10/Oct/2024 12:09:24] "GET /api/users/ HTTP/1.1" 500 203690
Internal Server Error: /api/users/
Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column users_user.code does not exist
LINE 1: ...ers_user"."is_superuser", "users_user"."user_id", "users_use...
                                                             ^
HINT:  Perhaps you meant to reference the column "users_user.role".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/rest_framework/authentication.py", line 127, in authenticate
    if not user or not user.is_active:
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/contrib/auth/middleware.py", line 37, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/contrib/auth/middleware.py", line 17, in get_user
    request._cached_user = auth.get_user(request)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/contrib/auth/__init__.py", line 216, in get_user
    user = backend.get_user(user_id)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/contrib/auth/backends.py", line 157, in get_user
    user = UserModel._default_manager.get(pk=user_id)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column users_user.code does not exist
LINE 1: ...ers_user"."is_superuser", "users_user"."user_id", "users_use...
                                                             ^
HINT:  Perhaps you meant to reference the column "users_user.role".

[10/Oct/2024 12:09:26] "GET /api/users/ HTTP/1.1" 500 203690
/home/czebravisualdata-api/htdocs/CzebraVisual/users/migrations/0001_initial.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 10, 2024 - 12:09:17
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/home/czebravisualdata-api/htdocs/CzebraVisual/users/migrations/0001_initial.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 10, 2024 - 12:12:14
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
[10/Oct/2024 12:14:35] "GET /api/users/ HTTP/1.1" 200 6020
[10/Oct/2024 12:15:22] "GET /api/users/ HTTP/1.1" 200 6020
[10/Oct/2024 12:15:23] "GET /api/users/users/ HTTP/1.1" 200 6312
/home/czebravisualdata-api/htdocs/CzebraVisual/requests/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).

You have 30 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions, token_blacklist, users.
Run 'python manage.py migrate' to apply them.
October 10, 2024 - 12:14:21
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 10, 2024 - 12:38:36
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 126, in inner_run
    autoreload.raise_last_exception()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/venv/lib/python3.10/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py", line 32, in <module>
    class User(AbstractBaseUser, PermissionsMixin):
  File "/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py", line 46, in User
    Company, 
NameError: name 'Company' is not defined
/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py changed, reloading.
Watching for file changes with StatReloader
[10/Oct/2024 12:40:07] "GET /api/users/users/ HTTP/1.1" 200 6347
[10/Oct/2024 12:40:10] "GET /api/users/users/ HTTP/1.1" 200 6347
[10/Oct/2024 12:40:15] "GET /api-auth/login/?next=/api/users/users/ HTTP/1.1" 200 2734
[10/Oct/2024 12:40:18] "POST /api-auth/login/ HTTP/1.1" 200 2981
[10/Oct/2024 12:40:23] "POST /api-auth/login/ HTTP/1.1" 302 0
[10/Oct/2024 12:40:23] "GET /api/users/users/ HTTP/1.1" 200 20682
[10/Oct/2024 12:40:46] "GET /api/requests/ HTTP/1.1" 200 6214
[10/Oct/2024 12:40:48] "GET /api/requests/companies/ HTTP/1.1" 200 12912
Bad Request: /api/requests/companies/
[10/Oct/2024 12:41:33] "POST /api/requests/companies/ HTTP/1.1" 400 13177
Bad Request: /api/requests/companies/
[10/Oct/2024 12:41:39] "POST /api/requests/companies/ HTTP/1.1" 400 13181
[10/Oct/2024 12:41:56] "POST /api/requests/companies/ HTTP/1.1" 201 13836
[10/Oct/2024 12:51:56] "GET /api/users/users/ HTTP/1.1" 200 20762
[10/Oct/2024 12:52:10] "GET /api/users/users/1/ HTTP/1.1" 200 22507
[10/Oct/2024 12:52:18] "PUT /api/users/users/1/ HTTP/1.1" 200 22421
[10/Oct/2024 12:52:22] "GET /api/users/users/1/ HTTP/1.1" 200 22421
/home/czebravisualdata-api/htdocs/CzebraVisual/users/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
October 10, 2024 - 12:39:48
Django version 5.1, using settings 'czebra.settings'
Starting development server at http://0.0.0.0:8100/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
[10/Oct/2024 13:00:33] "GET /api/users/users/1/ HTTP/1.1" 200 22421
[10/Oct/2024 13:00:37] "PUT /api/users/users/1/ HTTP/1.1" 200 22421
[10/Oct/2024 13:00:43] "PUT /api/users/users/1/ HTTP/1.1" 200 22427
